### ISSUE TITLE
Read timed out

### ISSUE THREAD

**Issue by alexanderkoller** [dialogos-project/dialogos-distribution#2]
When making an initial build of this project (with `gradlew run` after a fresh clone), Gradle downloads a large number of Jar files from jitpack. At a certain point, Gradle can crash with an error message like the following:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not download com.clt.audio.jar (com.github.coli-saar.dialogos:com.clt.audio:master-SNAPSHOT)
      > Could not get resource 'https://jitpack.io/com/github/coli-saar/dialogos/com.clt.audio/master-SNAPSHOT/com.clt.audio-master-13607d3bda-1.jar'.
         > Could not GET 'https://jitpack.io/com/github/coli-saar/dialogos/com.clt.audio/master-SNAPSHOT/com.clt.audio-master-13607d3bda-1.jar'.
            > Read timed out

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 54s
```

Rerunning `gradlew run` then picks up from that point. After rerunning it twice, my build process finished and I could run DialogOS. This makes me think that there is some timeout somewhere in the build script, and it is set too low.

Can we increase the timeout?

**Comment by alexanderkoller** [comment]
@akoehn

**Comment by timobaumann** [comment]
can be done according to https://stackoverflow.com/questions/37156568/increase-timeout-for-gradle-to-get-a-maven-dependency

**Comment by timobaumann** [comment]
this seems to actually time out within the jitpack.io infrastructure, not just on the client. Maybe put a remark somewhere to retry if it fails (and to
